server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    server_tokens off;
    resolver 127.0.0.11 valid=10s ipv6=off;

    location = /health { access_log off; default_type text/plain; return 200 "ok\n"; }
    location ~ ^/api/(orders|products)(/|$) {
        set $backend order-service:8081;
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://$backend;
        include /etc/nginx/proxy_params_commerce;
    }
    location ~ ^/api/inventory(/|$) {
        set $backend inventory-service:8082;
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://$backend;
        include /etc/nginx/proxy_params_commerce;
    }
    location ~ ^/api/payments(/|$) {
        set $backend payment-service:8083;
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://$backend;
        include /etc/nginx/proxy_params_commerce;
    }
    location /api/ { return 404; }
    location / { try_files $uri $uri/ /index.html; }
}
