spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5433/orders
    username: order_user
    password: order_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info