spring:
  application:
    name: order-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "com.lylecommerce.order.infrastructure.messaging"
        spring.json.value.default.type: "com.lylecommerce.order.infrastructure.messaging.InventoryReservedEvent"
        spring.json.use.type.headers: false

  datasource:
    url: jdbc:postgresql://localhost:5433/orders
    username: order_user
    password: order_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info