import { test, expect } from '@playwright/test';
// These tests deliberately use the real proxy/backend. There are no page.route mocks.
test('browse, persist bag, checkout and follow a real order', async ({ page }) => {
  const initialInventory = await (await page.request.get('/api/inventory')).json();
  const initialAvailable = initialInventory.find((item: { productId: string }) => item.productId === '22222222-2222-2222-2222-222222222222').availableQuantity;
  const consoleErrors: string[] = [];
  page.on('pageerror', error => consoleErrors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'The collection.' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Add Mechanical Keyboard to bag', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'View Mechanical Keyboard details' }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('dialog').getByText('USB-C connection', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Close product details' }).click();
  await page.getByRole('searchbox', { name: 'Search products' }).fill('keyboard');
  await expect(page.getByRole('button', { name: /^View .* details$/ })).toHaveCount(1);
  await page.getByRole('button', { name: 'Add Mechanical Keyboard to bag', exact: true }).click();
  await page.getByRole('link', { name: 'Shopping bag, 1 items' }).click();
  await page.getByRole('button', { name: 'Increase Mechanical Keyboard quantity' }).click();
  await expect(page.getByRole('spinbutton', { name: 'Mechanical Keyboard quantity' })).toHaveValue('2');
  await page.reload();
  await expect(page.getByRole('spinbutton', { name: 'Mechanical Keyboard quantity' })).toHaveValue('2');
  await expect(page.getByRole('link', { name: 'Continue to checkout' })).toBeEnabled();
  await page.getByRole('link', { name: 'Continue to checkout' }).click();
  await expect(page.getByRole('heading', { name: 'Make it yours.' })).toBeVisible();
  await page.getByRole('checkbox', { name: 'I understand this is a demo purchase.' }).check();
  const requestPromise = page.waitForRequest(request => request.url().endsWith('/api/orders') && request.method() === 'POST');
  await page.getByRole('button', { name: 'Place demo order' }).click();
  const sent = (await requestPromise).postDataJSON();
  expect(sent.items).toEqual([{ productId: '22222222-2222-2222-2222-222222222222', quantity: 2 }]);
  await expect(page.getByRole('heading', { name: 'Good things are yours.' })).toBeVisible();
  await expect(page.getByText('Demo payment succeeded', { exact: true })).toBeVisible();
  await expect(page.getByText('£159.98', { exact: true }).first()).toBeVisible();
  await expect(page.getByRole('link', { name: 'Shopping bag, 0 items' })).toBeVisible();
  const id = page.url().split('/orders/')[1];
  expect(id).toMatch(/^[\da-f-]{36}$/);
  // The displayed receipt must correspond to a real persisted backend order.
  const details = await page.request.get(`/api/orders/${id}/details`);
  expect(details.ok()).toBeTruthy();
  expect((await details.json()).order.status).toBe('CONFIRMED');
  await page.getByRole('link', { name: 'Order dashboard', exact: true }).click();
  await expect(page.getByRole('cell', { name: `#${id.slice(0, 8)}` })).toBeVisible();
  await page.getByRole('button', { name: `View order ${id.slice(0, 8)}` }).click();
  await expect(page.getByText('Demo payment succeeded', { exact: true })).toBeVisible();
  const inventoryRow = page.getByRole('row').filter({ has: page.getByRole('cell', { name: 'Mechanical Keyboard Workspace', exact: true }) });
  await expect(inventoryRow.getByRole('cell', { name: String(initialAvailable - 2), exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/dashboard-desktop.png', fullPage: true });
  expect(consoleErrors).toEqual([]);
});
test('mobile catalogue exposes filters and honest out-of-stock state', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await page.getByRole('button', { name: 'Audio', exact: true }).click();
  await expect(page.getByRole('button', { name: 'View Studio Headphones details' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Add Studio Headphones to bag' })).toBeDisabled();
  await page.getByRole('checkbox', { name: 'In stock only' }).check();
  await expect(page.getByRole('heading', { name: 'No essentials found.' })).toBeVisible();
  await page.getByRole('button', { name: 'Clear filters' }).click();
  await expect(page.getByRole('button', { name: /^View .* details$/ })).toHaveCount(6);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.screenshot({ path: 'test-results/catalogue-mobile.png', fullPage: true });
});
